version: 2.1
jobs:
  build_and_deploy:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
        docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t knight1988/node-serverless:latest .
      - run:
          name: Login
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: Push Docker image
          command: docker push knight1988/node-serverless:latest

workflows:
  version: 2
  build:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - master
                - /^release\//
